### PR TITLE
[FLINK-29427][ci][debug] Adds for loop to rerun LookupJoinITCase multiple times

### PR DESCRIPTION
**Pull request by XComp**
If you struggle to reproduce the test locally, you could try rerunning the test on Azure CI. It's not the most-straightforward approach to rerun a test in CI but it works. You can verify this PR's commit by running it without your change first. That run can be used to verify how likely the unstable test (i.e. `LookupJoinITCase`) would fail.

Including this commit and your fix would then show that your change actually fixed the instability. WDYT?

This is based on apache/flink#21365

### CODE REVIEW

**Comment by XComp** [comment]
I did a force push to explicitly specify the `flink-table/flink-table-planner` module instead of relying on the table module set since it would make the job run fail due to no test being selected for the other modules

**Comment by XComp** [comment]
Looks like I was too optimistic: The test ran 1052 times on AzureCI without failing once as well.

**Comment by smiralexan** [comment]
Hi @XComp, thanks for helping with reproducing the bug! Am I right, that you tried to run test without my fix, but error still was not reproduced? Maybe error happens only when test run together with other tests (some state exists from the runs of previous tests)? Maybe put 'for loop' for the whole module, etc. WDYT?

**Comment by XComp** [comment]
> Hi @XComp, thanks for helping with reproducing the bug! Am I right, that you tried to run test without my fix, but error still was not reproduced? Maybe error happens only when test run together with other tests (some state exists from the runs of previous tests)? Maybe put 'for loop' for the whole module, etc. WDYT?

Yes, that was the intention. But good point. I haven't thought of that :+1:

**Comment by XComp** [comment]
The test run with all LookupJoinITCase tests running in parallel didn't succeed, i.e. we couldn't reproduce the test failure with 483 repetitions. I rebased this branch and the base PR's branch. We haven't seen the issue of FLINK-29427 popping up for a few days (a week withouth any failure between Nov 23 and Nov 30). It just started recently again. So, maybe, we're lucky now? :thinking:

**Comment by XComp** [comment]
nope. still no success in reproducing it after 483 repetitions (https://dev.azure.com/asmirnov1/Flink/_build/results?buildId=70&view=results)

**Pull request closed without merging**
